export const en = {
    mainPage: 'Main page',
    authpage: 'Auth page',
    orders: 'Orders',
    loginHeader: 'Sign in to WorkerSearch',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    signIn: 'Sign In',
    mainPageTitle: 'Find any specialist online',
    searchPlaceholder: 'Who are you looking for?',
    find: 'Find',
    plumbing: 'Plumbing',
    cleaning: 'Cleaning',
    cooking: 'Cooking',
    order: 'Order',
    showPhoneNumber: 'Show phone number',
    price: 'Price (per hour)',
    viewDetails: 'View Details',
    ordersList: 'Check your orders',
    removeOrder: 'Remove order',
};

