export const en = {
    mainPage: 'WorkerSearch',
    authpage: 'Sign In',
    orders: 'Orders',
    loginHeader: 'Sign in to WorkerSearch',
    emailPlaceholder: 'Email address',
    passwordPlaceholder: 'Password',
    signIn: 'Sign In',
    mainPageTitle: 'Find any specialist online',
    searchPlaceholder: 'Who are you looking for?',
    find: 'Find',
    plumbing: 'Plumbing',
    cleaning: 'Cleaning',
    cooking: 'Cooking',
    order: 'Order',
    showPhoneNumber: 'Show phone number',
    price: 'Price (per hour)',
    viewDetails: 'View Details',
    ordersList: 'Your orders',
    removeOrder: 'Remove order',
    closed: 'Order is closed',
    password: 'Password',
    signInSuccess: 'Signed in successfully',
    signInError: 'Password or email is incorrect',
    findWorker: 'Find worker',
    register: 'Sign up',
    signOut: 'Sign out',
    registerHeader: 'Sign up to WorkerSearch',
    registerSuccess: 'Signed up successfully',
    namePlaceholder: 'Name',
    reenterPassword: 'Reenter password',
    passwordDontMatch: "Password doesn't match",
    signInActionsDescription: 'Find a professional or create a ticket to propose your services',
    tickets: 'Tickets',
    createTicket: 'Create ticket',
    ticketsList: 'Your tickets',
    create: 'Create',
    createTicketSuccess: 'Ticket successfully published',
    category: 'Type of service',
    descriprion: 'Descriprion',
    reset: 'Reset',
    phoneNumberPlaceholder: 'Phone number',
    invalidEmail: 'Email is invalid',
    fillForm: 'Filling in all form fields is required',
    priceWithCurrency: 'Price ($ per hour)',
    setDarkTheme: 'Dark theme',
    setLightTheme: 'Light theme',
    createdOrders: 'Created orders',
    recievedOrders: 'Recieved orders',
    closeOrder: 'Close order',
}
