export const uk = {
    mainPage: 'WorkerSearch',
    authpage: 'Увійти',
    orders: 'Замовлення',
    loginHeader: 'Увійдіть у WorkerSearch',
    emailPlaceholder: 'Електронна адреса',
    passwordPlaceholder: 'Пароль',
    signIn: 'Увійти',
    mainPageTitle: 'Знайдіть будь-якого спеціаліста',
    searchPlaceholder: 'Кого ви шукаєте?',
    find: 'Знайти',
    plumbing: 'Сантехніка',
    cleaning: 'Прибирання',
    equipmentRepair: 'Ремонт техніки',
    order: 'Замовити',
    showPhoneNumber: 'Показати номер телефону',
    price: 'Ціна (за годину)',
    viewDetails: 'Докладніше',
    ordersList: 'Ваші замовлення',
    removeOrder: 'Видалити замовлення',
    closed: 'Замовлення закрито',
    password: 'Пароль',
    signInSuccess: 'Авторизація успішна',
    signInError: 'Пароль або електронна адреса неправильні',
    findWorker: 'Знайти працівника',
    register: 'Зареєструватися',
    signOut: 'Вийти з аккаунта',
    registerHeader: 'Зареєструйтеся в WorkerSearch',
    registerSuccess: 'Реєстрація успішна',
    namePlaceholder: "Ім'я",
    reenterPassword: 'Повторно введіть пароль',
    passwordDontMatch: "Пароль не збігається",
    signInActionsDescription: 'Знайдіть професіонала або створіть квиток, щоб запропонувати свої послуги',
    tickets: 'Оголошення',
    createTicket: 'Створити квиток',
    ticketsList: 'Ваші квитки',
    create: 'Створити',
    createTicketSuccess: 'Квиток успішно опубліковано',
    category: 'Вид послуги',
    descriprion: 'Опис',
    reset: 'Скинути',
    phoneNumberPlaceholder: 'Номер телефону',
    invalidEmail: 'Невалідний email',
    fillForm: 'Необхідно заповнити всі поля форми',
    priceWithCurrency: 'Ціна ($ за годину)',
    setDarkTheme: 'Темну тема',
    setLightTheme: 'Світлу тема',
    createdOrders: 'Створені замовлення',
    recievedOrders: 'Отримані замовлення',
    closeOrder: 'Завершити замовлення',
    orderedBy: 'Замовник',
}
